apiVersion: batch/v1
kind: Job
metadata:
  name: notdynamo-bench-http-20260218024853
  namespace: notdynamo
  labels:
    app: notdynamo-bench
    benchmark-category: in-cluster
spec:
  ttlSecondsAfterFinished: 900
  backoffLimit: 0
  parallelism: 2
  completions: 2
  template:
    metadata:
      labels:
        app: notdynamo-bench
        benchmark-category: in-cluster
    spec:
      restartPolicy: Never
      containers:
        - name: bench
          image: 139643733075.dkr.ecr.us-west-2.amazonaws.com/notdynamo/notdynamo-bench:bench-20260218T024846Z
          imagePullPolicy: IfNotPresent
          args:
            - --scenario
            - e2e-http
            - --baseUrl
            - http://notdynamo-data.notdynamo.svc.cluster.local:8080
            - --operations
            - "4000"
            - --keyspace
            - "1000"
            - --threads
            - "8"
            - --readRatio
            - "0.90"
            - --distribution
            - "uniform"
            - --zipfTheta
            - "0.90"
            - --valueBytes
            - "256"
            - --preload
            - "false"
            - --connectTimeoutMs
            - "3000"
            - --requestTimeoutMs
            - "5000"
