apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notdynamo-data
spec:
  template:
    spec:
      topologySpreadConstraints: null
      affinity: null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notdynamo-control-plane
spec:
  template:
    spec:
      topologySpreadConstraints: null
      affinity: null
